import '@/app/globals.css';
import { Metadata } from 'next';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'about',
};

export default async function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
