import { Metadata } from 'next';
import '../globals.css';

export const metadata: Metadata = {
  title: 'about',
  description: 'Generated by create next app',
};

export default async function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <>{children}</>;
}
