import type { Metadata } from 'next';

import { Geist, Geist_Mono } from 'next/font/google';

import '@/app/globals.css';
import { Tanstack } from '@/app/tanstack';
import { ThemeContextProvider } from '@/context/ThemeContext';

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen antialiased`}
      >
        <Tanstack>
          <ThemeContextProvider>
            <div id="root">{children}</div>
          </ThemeContextProvider>
        </Tanstack>
      </body>
    </html>
  );
}
